<center>

# **Đồ án cuối kì**

# **Môn Lập trình cho khoa học dữ liệu**

## **Chủ đề: Phân tích chứng bệnh béo phì dựa trên<br>thói quen ăn uống và điều kiện thể chất**

</center>

<center>

# **Mục lục**

</center>

# **Các thư viện sử dụng**

In [2]:
# Libraries and Modules used
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt



---

# **Mô tả tập dữ liệu**

- Tập dữ liệu này được thu thập từ [Kaggle](https://www.kaggle.com/datasets/ankurbajaj9/obesity-levels?select=ObesityDataSet_raw_and_data_sinthetic.csv). Nhìn chung, tập dữ liệu mô tả sự dự đoán về mức độ béo phì của khoảng hơn 2000 người ở Mexico, Peru và Colombia vào năm 2019, dựa trên thói quen ăn uống và điều kiện thể chất của họ.

- Tập dữ liệu này là một tập dữ liệu mở được công bố dưới bản quyền [***Creative Commons CC-BY license***](https://creativecommons.org/licenses/by/4.0/), cho phép sử dụng không hạn chế dưới mọi hình thức, miễn là người dùng giữ nguyên tập dữ liệu gốc.

- 77% của dữ liệu được tổng hợp bằng công cụ Weka và bộ lọc SMOTE, trong khi đó 23% của dữ liệu được thu thập trực tiếp từ người dùng thông qua 1 nền tảng web.

- Qua việc xử lý và phân tích tập dữ liệu này, chúng ta có thể xây dựng nên các mô hình tính toán dự đoán mức độ béo phì của mỗi cá nhân, cũng như là tạo ra những hệ thống khuyến nghị nhằm kiểm soát nguy cơ béo phì trong cộng đồng.

---

# **Tiền xử lý dữ liệu**

## Đọc dữ liệu vào Dataframe

In [3]:
obe_df = pd.read_csv('obesity.csv', encoding='utf-8')
obe_df

Gender        Age    Height      Weight family_history_with_overweight  \
0     Female  21.000000  1.620000   64.000000                            yes   
1     Female  21.000000  1.520000   56.000000                            yes   
2       Male  23.000000  1.800000   77.000000                            yes   
3       Male  27.000000  1.800000   87.000000                             no   
4       Male  22.000000  1.780000   89.800000                             no   
...      ...        ...       ...         ...                            ...   
2106  Female  20.976842  1.710730  131.408528                            yes   
2107  Female  21.982942  1.748584  133.742943                            yes   
2108  Female  22.524036  1.752206  133.689352                            yes   
2109  Female  24.361936  1.739450  133.346641                            yes   
2110  Female  23.664709  1.738836  133.472641                            yes   

     FAVC  FCVC  NCP       CAEC SMOKE      CH2O  SCC       FAF       TUE  \
0      no   2.0  3.0  Sometimes    no  2.000000   no  0.000000  1.000000   
1      no   3.0  3.0  Sometimes   yes  3.000000  yes  3.000000  0.000000   
2      no   2.0  3.0  Sometimes    no  2.000000   no  2.000000  1.000000   
3      no   3.0  3.0  Sometimes    no  2.000000   no  2.000000  0.000000   
4      no   2.0  1.0  Sometimes    no  2.000000   no  0.000000  0.000000   
...   ...   ...  ...        ...   ...       ...  ...       ...       ...   
2106  yes   3.0  3.0  Sometimes    no  1.728139   no  1.676269  0.906247   
2107  yes   3.0  3.0  Sometimes    no  2.005130   no  1.341390  0.599270   
2108  yes   3.0  3.0  Sometimes    no  2.054193   no  1.414209  0.646288   
2109  yes   3.0  3.0  Sometimes    no  2.852339   no  1.139107  0.586035   
2110  yes   3.0  3.0  Sometimes    no  2.863513   no  1.026452  0.714137   

            CALC                 MTRANS           NObeyesdad  
0             no  Public_Transportation        Normal_Weight  
1      Sometimes  Public_Transportation        Normal_Weight  
2     Frequently  Public_Transportation        Normal_Weight  
3     Frequently                Walking   Overweight_Level_I  
4      Sometimes  Public_Transportation  Overweight_Level_II  
...          ...                    ...                  ...  
2106   Sometimes  Public_Transportation     Obesity_Type_III  
2107   Sometimes  Public_Transportation     Obesity_Type_III  
2108   Sometimes  Public_Transportation     Obesity_Type_III  
2109   Sometimes  Public_Transportation     Obesity_Type_III  
2110   Sometimes  Public_Transportation     Obesity_Type_III  

[2111 rows x 17 columns]

## Số dòng và số cột của tập dữ liệu

In [4]:
row = obe_df.shape[0]
col = obe_df.shape[1]
print('Số dòng:', row)
print('Số cột', col)

Số dòng: 2111
Số cột 17


## Ý nghĩa của mỗi dòng

- Mỗi dòng là thông tin cá nhân và thông tin về thói quen ăn uống cũng như là điều kiện thể chất của mỗi người được khảo sát.

## Kiểm tra các dòng bị trùng lắp

- Tập dữ liệu ở đây không có cột ID, hoặc đặc trưng nào đó tương tự như ID để phân biệt các người được khảo sát. Cho nên rất có thể sẽ có những dòng chứa thông tin và chỉ số của những người khác nhau nhưng giống hệt nhau.

- Kiểm tra

In [5]:
duplicated = obe_df.duplicated()
duplicated_line = obe_df[duplicated == True]
print('Số dòng bị trùng lắp:', len(duplicated_line))
duplicated_line

Số dòng bị trùng lắp: 24


Gender   Age  Height  Weight family_history_with_overweight FAVC  FCVC  \
98   Female  21.0    1.52    42.0                             no   no   3.0   
106  Female  25.0    1.57    55.0                             no  yes   2.0   
174    Male  21.0    1.62    70.0                             no  yes   2.0   
179    Male  21.0    1.62    70.0                             no  yes   2.0   
184    Male  21.0    1.62    70.0                             no  yes   2.0   
209  Female  22.0    1.69    65.0                            yes  yes   2.0   
309  Female  16.0    1.66    58.0                             no   no   2.0   
460  Female  18.0    1.62    55.0                            yes  yes   2.0   
467    Male  22.0    1.74    75.0                            yes  yes   3.0   
496    Male  18.0    1.72    53.0                            yes  yes   2.0   
527  Female  21.0    1.52    42.0                             no  yes   3.0   
659  Female  21.0    1.52    42.0                             no  yes   3.0   
663  Female  21.0    1.52    42.0                             no  yes   3.0   
763    Male  21.0    1.62    70.0                             no  yes   2.0   
764    Male  21.0    1.62    70.0                             no  yes   2.0   
824    Male  21.0    1.62    70.0                             no  yes   2.0   
830    Male  21.0    1.62    70.0                             no  yes   2.0   
831    Male  21.0    1.62    70.0                             no  yes   2.0   
832    Male  21.0    1.62    70.0                             no  yes   2.0   
833    Male  21.0    1.62    70.0                             no  yes   2.0   
834    Male  21.0    1.62    70.0                             no  yes   2.0   
921    Male  21.0    1.62    70.0                             no  yes   2.0   
922    Male  21.0    1.62    70.0                             no  yes   2.0   
923    Male  21.0    1.62    70.0                             no  yes   2.0   

     NCP        CAEC SMOKE  CH2O SCC  FAF  TUE       CALC  \
98   1.0  Frequently    no   1.0  no  0.0  0.0  Sometimes   
106  1.0   Sometimes    no   2.0  no  2.0  0.0  Sometimes   
174  1.0          no    no   3.0  no  1.0  0.0  Sometimes   
179  1.0          no    no   3.0  no  1.0  0.0  Sometimes   
184  1.0          no    no   3.0  no  1.0  0.0  Sometimes   
209  3.0   Sometimes    no   2.0  no  1.0  1.0  Sometimes   
309  1.0   Sometimes    no   1.0  no  0.0  1.0         no   
460  3.0  Frequently    no   1.0  no  1.0  1.0         no   
467  3.0  Frequently    no   1.0  no  1.0  0.0         no   
496  3.0   Sometimes    no   2.0  no  0.0  2.0  Sometimes   
527  1.0  Frequently    no   1.0  no  0.0  0.0  Sometimes   
659  1.0  Frequently    no   1.0  no  0.0  0.0  Sometimes   
663  1.0  Frequently    no   1.0  no  0.0  0.0  Sometimes   
763  1.0          no    no   3.0  no  1.0  0.0  Sometimes   
764  1.0          no    no   3.0  no  1.0  0.0  Sometimes   
824  1.0          no    no   3.0  no  1.0  0.0  Sometimes   
830  1.0          no    no   3.0  no  1.0  0.0  Sometimes   
831  1.0          no    no   3.0  no  1.0  0.0  Sometimes   
832  1.0          no    no   3.0  no  1.0  0.0  Sometimes   
833  1.0          no    no   3.0  no  1.0  0.0  Sometimes   
834  1.0          no    no   3.0  no  1.0  0.0  Sometimes   
921  1.0          no    no   3.0  no  1.0  0.0  Sometimes   
922  1.0          no    no   3.0  no  1.0  0.0  Sometimes   
923  1.0          no    no   3.0  no  1.0  0.0  Sometimes   

                    MTRANS           NObeyesdad  
98   Public_Transportation  Insufficient_Weight  
106  Public_Transportation        Normal_Weight  
174  Public_Transportation   Overweight_Level_I  
179  Public_Transportation   Overweight_Level_I  
184  Public_Transportation   Overweight_Level_I  
209  Public_Transportation        Normal_Weight  
309                Walking        Normal_Weight  
460  Public_Transportation        Normal_Weight  
467             Automobile        Normal_Weight  
496

- Ở đây có 24 dòng bị trùng lắp, có thể đây là thông tin của những người khác nhau hoàn toàn (hoặc có thể giống nhau). Tuy nhiên, ta có thể cho rằng đây là những người riêng biệt và xử lý như bình thường mà không cần loại bỏ các dòng bị trùng lắp này.

## Ý nghĩa của mỗi cột

In [6]:
des_df = pd.read_csv('description.csv')
des_df = des_df.iloc[:, :2]
des_df

Đặc trưng  \
0                           Gender   
1                              Age   
2                           Height   
3                           Weight   
4   family_history_with_overweight   
5                             FAVC   
6                             FCVC   
7                              NCP   
8                             CAEC   
9                            SMOKE   
10                            CH2O   
11                             SCC   
12                             FAF   
13                             TUE   
14                            CALC   
15                          MTRANS   
16                      NObeyesdad   

                                            Mô tả  
0                                       Giới tính  
1                                            Tuổi  
2                                       Chiều cao  
3                                        Cân nặng  
4       Gia đình có tiền sử bị thừa cân hay không  
5      Có thường xuyên ăn thức ăn nhanh hay không  
6                              Tần suất ăn rau củ  
7                                 Số bữa ăn chính  
8       Có ăn vặt giữa các bữa ăn chính hay không  
9                          Có hút thuốc hay không  
10                       Lượng nước uống mỗi ngày  
11     Có kiểm soát lượng calo tiêu thụ hay không  
12                    Tần suất hoạt động thể chất  
13  Thời gian sử dụng thiết bị công nghệ mỗi ngày  
14                             Có uống rượu không  
15                 Phương tiện giao thông sử dụng  
16                                 Mức độ béo phì

- Các đặc trưng liên quan đến thói quen ăn uống:

In [7]:
eh_df = des_df.iloc[[5,6,7,8,10,14], [0,1]]
eh_df.reset_index().iloc[:, 1:]

Đặc trưng                                       Mô tả
0      FAVC  Có thường xuyên ăn thức ăn nhanh hay không
1      FCVC                          Tần suất ăn rau củ
2       NCP                             Số bữa ăn chính
3      CAEC   Có ăn vặt giữa các bữa ăn chính hay không
4      CH2O                    Lượng nước uống mỗi ngày
5      CALC                          Có uống rượu không

- Các đặc trưng liên quan đến điều kiện thể chất:

In [8]:
pc_df = des_df.iloc[[11,12,13,15], [0,1]]
pc_df.reset_index().iloc[:, 1:]

Đặc trưng                                          Mô tả
0       SCC     Có kiểm soát lượng calo tiêu thụ hay không
1       FAF                    Tần suất hoạt động thể chất
2       TUE  Thời gian sử dụng thiết bị công nghệ mỗi ngày
3    MTRANS                 Phương tiện giao thông sử dụng

## Kiểm tra kiểu dữ liệu của các cột và điều chỉnh cho phù hợp

- Kiểm tra kiểu dữ liệu của từng cột

In [9]:
obe_df.dtypes

Gender                             object
Age                               float64
Height                            float64
Weight                            float64
family_history_with_overweight     object
FAVC                               object
FCVC                              float64
NCP                               float64
CAEC                               object
SMOKE                              object
CH2O                              float64
SCC                                object
FAF                               float64
TUE                               float64
CALC                               object
MTRANS                             object
NObeyesdad                         object
dtype: object

---

In [10]:
obe_df['Age'].unique()

array([21.      , 23.      , 27.      , ..., 22.524036, 24.361936,
       23.664709])

- Ta thấy ở cột Age, có những hàng đang không phải là kiểu số nguyên nên ta sẽ làm tròn xuống (vì chưa đủ tuổi) của tuổi tác và sau đó ép kiểu về int.

In [11]:
obe_df['Age'] = np.floor(obe_df['Age'])
obe_df['Age'] = obe_df['Age'].astype(int)
obe_df['Age']

0       21
1       21
2       23
3       27
4       22
        ..
2106    20
2107    21
2108    22
2109    24
2110    23
Name: Age, Length: 2111, dtype: int32

---

In [12]:
obe_df['Height'].unique()

array([1.62    , 1.52    , 1.8     , ..., 1.752206, 1.73945 , 1.738836])

- ...

In [13]:
obe_df['Height'] = np.round(obe_df['Height'], 2)
obe_df['Height']

0       1.62
1       1.52
2       1.80
3       1.80
4       1.78
        ... 
2106    1.71
2107    1.75
2108    1.75
2109    1.74
2110    1.74
Name: Height, Length: 2111, dtype: float64

---

In [14]:
obe_df['Weight'].unique()

array([ 64.      ,  56.      ,  77.      , ..., 133.689352, 133.346641,
       133.472641])

- ...

In [15]:
obe_df['Weight'] = np.round(obe_df['Weight'], 1)
obe_df['Weight']

0        64.0
1        56.0
2        77.0
3        87.0
4        89.8
        ...  
2106    131.4
2107    133.7
2108    133.7
2109    133.3
2110    133.5
Name: Weight, Length: 2111, dtype: float64

---

In [16]:
obe_df['FCVC'].unique()

array([2.      , 3.      , 1.      , 2.450218, 2.880161, 2.00876 ,
       2.596579, 2.591439, 2.392665, 1.123939, 2.027574, 2.658112,
       2.88626 , 2.714447, 2.750715, 1.4925  , 2.205439, 2.059138,
       2.310423, 2.823179, 2.052932, 2.596364, 2.767731, 2.815157,
       2.737762, 2.568063, 2.524428, 2.971574, 1.0816  , 1.270448,
       1.344854, 2.959658, 2.725282, 2.844607, 2.44004 , 2.432302,
       2.592247, 2.449267, 2.929889, 2.015258, 1.031149, 1.592183,
       1.21498 , 1.522001, 2.703436, 2.362918, 2.14084 , 2.5596  ,
       2.336044, 1.813234, 2.724285, 2.71897 , 1.133844, 1.757466,
       2.979383, 2.204914, 2.927218, 2.88853 , 2.890535, 2.530066,
       2.241606, 1.003566, 2.652779, 2.897899, 2.483979, 2.945967,
       2.478891, 2.784464, 1.005578, 2.938031, 2.842102, 1.889199,
       2.943749, 2.33998 , 1.950742, 2.277436, 2.371338, 2.984425,
       2.977018, 2.663421, 2.753752, 2.318355, 2.594653, 2.886157,
       2.967853, 2.619835, 1.053534, 2.530233, 2.8813  , 2.824

- ...

In [17]:
obe_df['FCVC'] = np.round(obe_df['FCVC'], 0)
obe_df['FCVC'] = obe_df['FCVC'].astype(int)
obe_df['FCVC'] = obe_df['FCVC'].replace([1, 2, 3], ['Rarely', 'Sometimes', 'Always'])
obe_df['FCVC']

0       Sometimes
1          Always
2       Sometimes
3          Always
4       Sometimes
          ...    
2106       Always
2107       Always
2108       Always
2109       Always
2110       Always
Name: FCVC, Length: 2111, dtype: object

---

In [18]:
obe_df['NCP'].unique()

array([3.      , 1.      , 4.      , 3.28926 , 3.995147, 1.72626 ,
       2.581015, 1.600812, 1.73762 , 1.10548 , 2.0846  , 1.894384,
       2.857787, 3.765526, 3.285167, 3.691226, 3.156153, 1.07976 ,
       3.559841, 3.891994, 3.240578, 3.904858, 3.11158 , 3.590039,
       2.057935, 3.558637, 2.000986, 3.821168, 3.897078, 3.092116,
       3.286431, 3.592415, 3.754599, 3.566082, 3.725797, 3.520555,
       3.731212, 1.259803, 1.273128, 3.304123, 3.647154, 3.300666,
       3.535016, 1.717608, 2.884479, 3.626815, 1.473088, 3.16645 ,
       3.494849, 2.99321 , 2.127797, 3.90779 , 3.699594, 3.179995,
       1.075553, 3.238258, 3.804944, 1.630846, 3.762778, 3.371832,
       2.705445, 3.34175 , 2.217651, 2.893778, 3.502604, 3.998766,
       3.193671, 1.69608 , 2.812377, 1.612747, 1.082304, 1.882158,
       2.326233, 1.989398, 1.735493, 2.974568, 3.715118, 3.489918,
       3.378859, 3.263201, 3.994588, 3.24934 , 3.087544, 1.163666,
       3.409363, 3.281391, 3.98525 , 3.207071, 3.471536, 3.488

- ...

In [19]:
obe_df['NCP'] = np.round(obe_df['NCP'], 0)
obe_df['NCP'] = obe_df['NCP'].astype(int)
obe_df['NCP']

0       3
1       3
2       3
3       3
4       1
       ..
2106    3
2107    3
2108    3
2109    3
2110    3
Name: NCP, Length: 2111, dtype: int32

---

In [20]:
obe_df['CH2O'].unique()

array([2.      , 3.      , 1.      , ..., 2.054193, 2.852339, 2.863513])

- ...

In [21]:
obe_df['CH2O'] = np.round(obe_df['CH2O'], 1)
obe_df['CH2O']

0       2.0
1       3.0
2       2.0
3       2.0
4       2.0
       ... 
2106    1.7
2107    2.0
2108    2.1
2109    2.9
2110    2.9
Name: CH2O, Length: 2111, dtype: float64

---

In [22]:
obe_df['FAF'].unique()

array([0.      , 3.      , 2.      , ..., 1.414209, 1.139107, 1.026452])

- ...

In [23]:
obe_df['FAF'] = np.round(obe_df['FAF'], 0)
obe_df['FAF'] = obe_df['FAF'].astype(int)
obe_df['FAF'] = obe_df['FAF'].replace([0, 1, 2, 3], ['no physical activity', '1-2 days', '3-4 days', '5-6 days'])
obe_df['FAF']

0       no physical activity
1                   5-6 days
2                   3-4 days
3                   3-4 days
4       no physical activity
                ...         
2106                3-4 days
2107                1-2 days
2108                1-2 days
2109                1-2 days
2110                1-2 days
Name: FAF, Length: 2111, dtype: object

---

In [24]:
obe_df['TUE'].unique()

array([1.      , 0.      , 2.      , ..., 0.646288, 0.586035, 0.714137])

- ...

In [25]:
obe_df['TUE'] = np.round(obe_df['TUE'], 0)
obe_df['TUE'] = obe_df['TUE'].astype(int)
obe_df['TUE'] = obe_df['TUE'].replace([0, 1, 2], ['0-2 hours', '3-5 hours', 'more than 5 hours'])
obe_df['TUE']

0       3-5 hours
1       0-2 hours
2       3-5 hours
3       0-2 hours
4       0-2 hours
          ...    
2106    3-5 hours
2107    3-5 hours
2108    3-5 hours
2109    3-5 hours
2110    3-5 hours
Name: TUE, Length: 2111, dtype: object

---

- Kiểm tra các cột còn lại

In [26]:
obe_df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [27]:
obe_df['family_history_with_overweight'].unique()

array(['yes', 'no'], dtype=object)

In [28]:
obe_df['FAVC'].unique()

array(['no', 'yes'], dtype=object)

In [29]:
obe_df['CAEC'].unique()

array(['Sometimes', 'Frequently', 'Always', 'no'], dtype=object)

In [30]:
obe_df['SMOKE'].unique()

array(['no', 'yes'], dtype=object)

In [31]:
obe_df['SCC'].unique()

array(['no', 'yes'], dtype=object)

In [32]:
obe_df['CALC'].unique()

array(['no', 'Sometimes', 'Frequently', 'Always'], dtype=object)

In [33]:
obe_df['MTRANS'].unique()

array(['Public_Transportation', 'Walking', 'Automobile', 'Motorbike',
       'Bike'], dtype=object)

In [34]:
obe_df['NObeyesdad'].unique()

array(['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II',
       'Obesity_Type_I', 'Insufficient_Weight', 'Obesity_Type_II',
       'Obesity_Type_III'], dtype=object)

- Các cột dữ liệu còn lại có kiểu dữ liệu và giá trị phù hợp cho nên ta sẽ không cần điều chỉnh nữa.

- Kiểm tra lại kiểu dữ liệu của từng cột

In [35]:
obe_df.dtypes

Gender                             object
Age                                 int32
Height                            float64
Weight                            float64
family_history_with_overweight     object
FAVC                               object
FCVC                               object
NCP                                 int32
CAEC                               object
SMOKE                              object
CH2O                              float64
SCC                                object
FAF                                object
TUE                                object
CALC                               object
MTRANS                             object
NObeyesdad                         object
dtype: object

- Kiểm tra lại toàn bộ tập dữ liệu

In [36]:
obe_df

Gender  Age  Height  Weight family_history_with_overweight FAVC  \
0     Female   21    1.62    64.0                            yes   no   
1     Female   21    1.52    56.0                            yes   no   
2       Male   23    1.80    77.0                            yes   no   
3       Male   27    1.80    87.0                             no   no   
4       Male   22    1.78    89.8                             no   no   
...      ...  ...     ...     ...                            ...  ...   
2106  Female   20    1.71   131.4                            yes  yes   
2107  Female   21    1.75   133.7                            yes  yes   
2108  Female   22    1.75   133.7                            yes  yes   
2109  Female   24    1.74   133.3                            yes  yes   
2110  Female   23    1.74   133.5                            yes  yes   

           FCVC  NCP       CAEC SMOKE  CH2O  SCC                   FAF  \
0     Sometimes    3  Sometimes    no   2.0   no  no physical activity   
1        Always    3  Sometimes   yes   3.0  yes              5-6 days   
2     Sometimes    3  Sometimes    no   2.0   no              3-4 days   
3        Always    3  Sometimes    no   2.0   no              3-4 days   
4     Sometimes    1  Sometimes    no   2.0   no  no physical activity   
...         ...  ...        ...   ...   ...  ...                   ...   
2106     Always    3  Sometimes    no   1.7   no              3-4 days   
2107     Always    3  Sometimes    no   2.0   no              1-2 days   
2108     Always    3  Sometimes    no   2.1   no              1-2 days   
2109     Always    3  Sometimes    no   2.9   no              1-2 days   
2110     Always    3  Sometimes    no   2.9   no              1-2 days   

            TUE        CALC                 MTRANS           NObeyesdad  
0     3-5 hours          no  Public_Transportation        Normal_Weight  
1     0-2 hours   Sometimes  Public_Transportation        Normal_Weight  
2     3-5 hours  Frequently  Public_Transportation        Normal_Weight  
3     0-2 hours  Frequently                Walking   Overweight_Level_I  
4     0-2 hours   Sometimes  Public_Transportation  Overweight_Level_II  
...         ...         ...                    ...                  ...  
2106  3-5 hours   Sometimes  Public_Transportation     Obesity_Type_III  
2107  3-5 hours   Sometimes  Public_Transportation     Obesity_Type_III  
2108  3-5 hours   Sometimes  Public_Transportation     Obesity_Type_III  
2109  3-5 hours   Sometimes  Public_Transportation     Obesity_Type_III  
2110  3-5 hours   Sometimes  Public_Transportation     Obesity_Type_III  

[2111 rows x 17 columns]

---

## Tìm sự phân phối của các cột dữ liệu kiểu số

- Chọn những cột có kiểu dữ liệu số để tính phần trăm giá trị bị mất, giá trị nhỏ nhất, giá trị lớn nhất của mỗi cột dữ liệu.

In [37]:
num_df = obe_df.select_dtypes(include = 'number')

mising_percentage = (num_df.isna().sum() / row) * 100       # tỉ lệ giá trị bị thiếu
min_values = np.min(num_df)                                 # các giá trị nhỏ nhất
max_values = np.max(num_df)                                 # các giá trị lớn nhất

num_cols_distribution = pd.DataFrame(data = np.array((mising_percentage, min_values, max_values)),
                                                      columns = num_df.columns,
                                                      index = ['mising percentage', 'min', 'max'])
num_cols_distribution

Age  Height  Weight  NCP  CH2O
mising percentage   0.0    0.00     0.0  0.0   0.0
min                14.0    1.45    39.0  1.0   1.0
max                61.0    1.98   173.0  4.0   3.0

- Có vẻ như không có gì bất thường đối với dữ liệu của các cột dữ liệu kiểu số.

## Tìm sự phân phối của các cột dữ liệu kiểu phân loại

- Chọn những cột có kiểu dữ liệu phân loại để tính phần trăm giá trị bị mất, tìm số giá trị riêng biệt, và các giá trị riêng biệt của mỗi cột dữ liệu.

In [38]:
cat_df = obe_df.select_dtypes(include = 'object')

mising_percentage = (cat_df.isna().sum() / row) * 100           # tỉ lệ giá trị bị thiếu
num_diff_vals = cat_df.dropna().nunique()                       # số giá trị khác nhau
diff_vals = cat_df.apply(lambda col: col.dropna().unique())     # các giá trị khác nhau

cat_cols_distribution = pd.DataFrame(data = np.array((mising_percentage, num_diff_vals, diff_vals)),
                                     columns = cat_df.columns,
                                     index = ['mising percentage', 'num_diff_vals', 'diff_vals'])
cat_cols_distribution

Gender family_history_with_overweight       FAVC  \
mising percentage             0.0                            0.0        0.0   
num_diff_vals                   2                              2          2   
diff_vals          [Female, Male]                      [yes, no]  [no, yes]   

                                          FCVC  \
mising percentage                          0.0   
num_diff_vals                                3   
diff_vals          [Sometimes, Always, Rarely]   

                                                  CAEC      SMOKE        SCC  \
mising percentage                                  0.0        0.0        0.0   
num_diff_vals                                        4          2          2   
diff_vals          [Sometimes, Frequently, Always, no]  [no, yes]  [no, yes]   

                                                                 FAF  \
mising percentage                                                0.0   
num_diff_vals                                                      4   
diff_vals          [no physical activity, 5-6 days, 3-4 days, 1-2...   

                                                         TUE  \
mising percentage                                        0.0   
num_diff_vals                                              3   
diff_vals          [3-5 hours, 0-2 hours, more than 5 hours]   

                                                  CALC  \
mising percentage                                  0.0   
num_diff_vals                                        4   
diff_vals          [no, Sometimes, Frequently, Always]   

                                                              MTRANS  \
mising percentage                                                0.0   
num_diff_vals                                                      5   
diff_vals          [Public_Transportation, Walking, Automobile, M...   

                                                          NObeyesdad  
mising percentage                                                0.0  
num_diff_vals                                                      7  
diff_vals          [Normal_Weight, Overweight_Level_I, Overweight...

- Có vẻ như không có gì bất thường đối với dữ liệu của các cột dữ liệu kiểu phân loại.

## Xử lý các dòng bị thiếu dữ liệu

- Ở đây tỉ lệ giá trị bị thiếu của tất cả các cột đều là 0%, cho nên không cần xử lý các dòng bị thiếu dữ liệu.

---

# **Phân tích dữ liệu**

## **Câu hỏi số 1**

- (Nhập câu hỏi)
- (Lợi ích của việc tìm câu trả lời cho câu hỏi này)

### Tiền xử lý

In [39]:
normal = obe_df[obe_df['NObeyesdad'] == 'Normal_Weight']
normal

Gender  Age  Height  Weight family_history_with_overweight FAVC  \
0    Female   21    1.62    64.0                            yes   no   
1    Female   21    1.52    56.0                            yes   no   
2      Male   23    1.80    77.0                            yes   no   
5      Male   29    1.62    53.0                             no  yes   
6    Female   23    1.50    55.0                            yes  yes   
..      ...  ...     ...     ...                            ...  ...   
491    Male   25    1.66    68.0                             no  yes   
493    Male   20    1.80    65.0                             no  yes   
494  Female   18    1.67    66.0                             no  yes   
495    Male   19    1.80    60.0                            yes  yes   
497    Male   20    1.56    45.0                             no   no   

          FCVC  NCP        CAEC SMOKE  CH2O  SCC                   FAF  \
0    Sometimes    3   Sometimes    no   2.0   no  no physical activity   
1       Always    3   Sometimes   yes   3.0  yes              5-6 days   
2    Sometimes    3   Sometimes    no   2.0   no              3-4 days   
5    Sometimes    3   Sometimes    no   2.0   no  no physical activity   
6       Always    3   Sometimes    no   2.0   no              1-2 days   
..         ...  ...         ...   ...   ...  ...                   ...   
491  Sometimes    3   Sometimes   yes   1.0   no              1-2 days   
493  Sometimes    3  Frequently    no   1.0   no              3-4 days   
494     Always    3   Sometimes    no   2.0   no  no physical activity   
495     Always    1      Always    no   1.0  yes  no physical activity   
497  Sometimes    3   Sometimes    no   2.0   no              1-2 days   

           TUE        CALC                 MTRANS     NObeyesdad  
0    3-5 hours          no  Public_Transportation  Normal_Weight  
1    0-2 hours   Sometimes  Public_Transportation  Normal_Weight  
2    3-5 hours  Frequently  Public_Transportation  Normal_Weight  
5    0-2 hours   Sometimes             Automobile  Normal_Weight  
6    0-2 hours   Sometimes              Motorbike  Normal_Weight  
..         ...         ...                    ...            ...  
491  3-5 hours   Sometimes  Public_Transportation  Normal_Weight  
493  0-2 hours   Sometimes              Motorbike  Normal_Weight  
494  0-2 hours   Sometimes  Public_Transportation  Normal_Weight  
495  0-2 hours          no              Motorbike  Normal_Weight  
497  3-5 hours   Sometimes  Public_Transportation  Normal_Weight  

[287 rows x 17 columns]

### Phân tích

In [40]:
most_FAVC = []
most_FCVC = []
most_NCP  = []
most_CAEC = []
most_CH2O = []
most_CALC = []

normal['Age'].value_counts().sort_index()

14     1
16     6
17    18
18    43
19    34
20    30
21    45
22    25
23    28
24    10
25    11
26    10
27     3
29     3
30     2
31     2
32     1
33     6
34     1
35     1
36     1
38     4
51     1
61     1
Name: Age, dtype: int64

In [41]:
most_SCC = []
most_FAF = []
most_TUE = []
most_MTRANS = []

### Trực quan hóa

### Trả lời câu hỏi

- (Nhập câu trả lời và giải thích)

---

## **Câu hỏi số 2**

- (Nhập câu hỏi)
- (Lợi ích của việc tìm câu trả lời cho câu hỏi này)

### Tiền xử lý

### Phân tích

### Trực quan hóa

### Trả lời câu hỏi

- (Nhập câu trả lời và giải thích)

---

## **Câu hỏi số 3**

- (Nhập câu hỏi)
- (Lợi ích của việc tìm câu trả lời cho câu hỏi này)

### Tiền xử lý

### Phân tích

### Trực quan hóa

### Trả lời câu hỏi

- (Nhập câu trả lời và giải thích)

---

## **Câu hỏi số 4**

- (Nhập câu hỏi)
- (Lợi ích của việc tìm câu trả lời cho câu hỏi này)

### Tiền xử lý

### Phân tích

### Trực quan hóa

### Trả lời câu hỏi

- (Nhập câu trả lời và giải thích)

---

# **Đôi điều về đồ án**

- Mỗi thành viên gặp khó khăn gì?
- Mỗi thành viên học được những gì?
- Nếu có thêm thời gian, sẽ làm những gì?

---

# **Các nguồn tham khảo**

https://www.kaggle.com/datasets/ankurbajaj9/obesity-levels?select=ObesityDataSet_raw_and_data_sinthetic.csv

